Builder pattern for UIAttribute
reform-org/reform pull request #130
Opened 2023-01-25 11:08 UTC by Oshgnacknak

This supports Ints and Strings as well als Optionals of both

2023-01-25 13:21 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/SalaryChangesPage.scala
Jetzt haben wir ja zwei pattern die Koexistieren, können wir nicht select und date auch irgendwie über das factory pattern abbilden?

2023-01-25 13:22 UTC, lukasschreiber commented
Und der Code muss noch formattiert werden

2023-01-25 13:31 UTC, mohe2015 requested changes
Except for Lukas' comment you need to format the code. I will look into the selenium failure as it seems unrelated to this change.

2023-01-25 13:44 UTC, Oshgnacknak commented on js/src/main/scala/webapp/pages/SalaryChangesPage.scala
I ignored them for now. My plan is to also involve the new types into the builder

2023-01-27 21:25 UTC, lukasschreiber commented on js/src/main/scala/webapp/Routes.scala
> +    case WebRTCHandling(_)   => Root / "webrtc";
Was macht das?

2023-01-27 21:34 UTC, mohe2015 commented on js/src/main/scala/webapp/pages/WebRTCHandling.scala
> +case class WebRTCHandling(private val state: Var[State] = Var(Init)) extends Page {
@lukasschreiber the state is stored here and the underscore at that other place pattern matches that value. Otherwise it doesn't compile

2023-01-28 00:02 UTC, mohe2015 reviewed
.

2023-01-28 00:02 UTC, mohe2015 approved these changes
test

2023-01-29 21:13 UTC, mohe2015 commented on package.json
> -    "pdf-lib": "^1.17.1",
this looks kinda wrong

2023-01-29 21:18 UTC, Oshgnacknak commented on package.json
> -    "pdf-lib": "^1.17.1",
yes

2023-01-29 21:35 UTC, mohe2015 commented on js/src/main/scala/webapp/pages/ProjectsPage.scala
> +  .withDefaultValue("no account")
for now the default here needs to be "" otherwise the edit fields are broken

2023-01-29 21:35 UTC, mohe2015 commented on js/src/main/scala/webapp/pages/UsersPage.scala
> +  .withDefaultValue("no comment")
same here

2023-01-29 21:35 UTC, mohe2015 commented
And also remove the pdf please

2023-01-30 00:11 UTC, mohe2015 commented
Otherwise the main branch unfortunately has gotten some package lock updates so you need to regenerate that *again*

2023-01-30 15:07 UTC, merged