Better form validation
reform-org/reform pull request #140
Opened 2023-01-26 15:46 UTC by mohe2015

2023-01-26 15:52 UTC, mohe2015 commented
I would leave further design work to Julia

2023-01-26 20:29 UTC, mohe2015 commented
**USE REBASE AND MERGE INSTEAD OF SQUASH MERGE**

2023-01-27 18:56 UTC, JuliaSelua reviewed
Number Fields sehen gut aus, können aber  sein

Mit Ragnar sollten wir die required Felder nochmal checken (evtl account, comment, ... auch leer möglich machen)

Conflict Resolution sieht deutlich besser aus

Background Sync funktioniert

2023-01-27 18:58 UTC, JuliaSelua reviewed
Number Fields sehen gut aus, können aber 0 sein

Mit Ragnar sollten wir die required Felder nochmal checken (evtl account, comment, ... auch leer möglich machen)

Conflict Resolution sieht deutlich besser aus

Background Sync funktioniert

2023-01-27 19:13 UTC, mohe2015 commented
> Number Fields sehen gut aus, können aber 0 sein

Fixed that in 88e73f1072ffc86a486f25c536f59a757acbeea2
> 
> Mit Ragnar sollten wir die required Felder nochmal checken (evtl account, comment, ... auch leer möglich machen)

Actually this was also a bug. Should be fixed in 62ae053522c2f1dde03e9bdb5b52dbf5ccc7682b

> Conflict Resolution sieht deutlich besser aus
> 
> Background Sync funktioniert

2023-01-27 21:24 UTC, lukasschreiber requested changes

2023-01-27 21:24 UTC, lukasschreiber commented on js/src/main/scala/webapp/Services.scala
> -  lazy val webrtc: WebRTCService.type
Hmmm, warum hast du das geändert? Das wird ordentlich Konflikte mit meinem Connection refactor geben.

2023-01-27 21:24 UTC, lukasschreiber commented on shared/src/main/scala/webapp/Repositories.scala
> +  val lociRegistry: Registry = new Registry
auf dem Register selbst sollte eigentlich nicht gearbeitet werden, da ja noch weitere Infos wie das Alias verwaltet werden müssen, die gar nicht darin gespeichert werden können. Das muss in eine eigene Klasse, würde das erstmal so lassen wie vorher.

2023-01-27 21:30 UTC, mohe2015 commented on js/src/main/scala/webapp/Services.scala
> -  lazy val webrtc: WebRTCService.type
Weil sonst die Repositories nicht geladen werden, sobald das WebRTC connected ist und wenn du die seiten frisch neugeladen hast dann nichts gesynct wird

2023-01-27 21:31 UTC, mohe2015 commented on js/src/main/scala/webapp/Services.scala
> -  lazy val webrtc: WebRTCService.type
Maybe not making it lazy also works. I would need to try that

2023-01-27 21:53 UTC, lukasschreiber submitted a review, later dismissed

2023-01-27 21:53 UTC, lukasschreiber commented
Passt dann von meiner Seite

2023-01-27 22:03 UTC, Oshgnacknak approved these changes
lgtm

We need to adapt the UIAttributeBuilder

2023-01-28 16:58 UTC, merged