Support amounts of money with BigDecimals
reform-org/reform pull request #233
Opened 2023-02-13 21:33 UTC by Oshgnacknak

Closes #228
Closes #209

2023-02-13 21:41 UTC, lukasschreiber requested changes

2023-02-13 21:41 UTC, lukasschreiber commented on shared/src/main/scala/webapp/utils/Money.scala
> +    def toMoneyString: String = df.format(self) + "€"
Leerzeichen zwischen Zahl und €

2023-02-13 22:06 UTC, lukasschreiber commented
Könnte mir vorstellen, dass es für den Nutzer verwirrend ist, wenn im editmode ein . als Dezimaltrennzeichen ist und im displaymode ein ,

2023-02-14 12:27 UTC, mohe2015 commented on shared/src/main/scala/webapp/utils/Money.scala
> +    symbols.setDecimalSeparator(',')
application should be localized in english so maybe also use english here? (for dates I would still use the german format as the english format is just too ambigous with the m/d/y and d/m/y

2023-02-14 14:14 UTC, Oshgnacknak commented on shared/src/main/scala/webapp/utils/Money.scala
> +    symbols.setDecimalSeparator(',')
We could let the browser do it: https://stackoverflow.com/a/16233919
This is out of scope for now

2023-02-14 14:17 UTC, Oshgnacknak commented
> Könnte mir vorstellen, dass es für den Nutzer verwirrend ist, wenn im editmode ein . als Dezimaltrennzeichen ist und im displaymode ein ,

Zumindest FF kommt damit klar
![image](https://user-images.githubusercontent.com/41330025/218764285-95faa519-ef8f-4c93-b3c4-1227df9259ac.png)
![image](https://user-images.githubusercontent.com/41330025/218764338-2df42f4d-2cb6-4012-9c5c-c6a0954b91e5.png)

2023-02-14 14:26 UTC, lukasschreiber approved these changes

2023-02-14 14:26 UTC, merged