Import
reform-org/reform pull request #234
Opened 2023-02-13 23:35 UTC by lukasschreiber

2023-02-14 10:36 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/HomePage.scala
> +                  importIndexedDBJson(json)(using repositories)
some kind of feedback is needed to show the user that the import was successful

2023-02-14 10:36 UTC, lukasschreiber commented on shared/src/main/scala/webapp/repo/Repository.scala
> +  given magicCodec: JsonValueCodec[Repository[A]] =
the codec should have a name that implies, that the codec should not be used for anything other than importing from json

2023-02-14 13:12 UTC, Oshgnacknak requested changes

2023-02-14 13:12 UTC, Oshgnacknak commented on js/src/main/scala/webapp/pages/HomePage.scala
> +            val fileList = document.querySelector("#import-file").asInstanceOf[HTMLInputElement].files
Im sure we don't need to query select thanks to `outwatch`. Just Let the user input into a `Var` - or does this not work with file selects?

2023-02-14 13:12 UTC, Oshgnacknak commented on utils.js
> +export const downloadJson = (name, text) => {
we might want to try https://stackoverflow.com/a/7208039.
Seems cleaner to me

2023-02-14 16:02 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/HomePage.scala
> +            val fileList = document.querySelector("#import-file").asInstanceOf[HTMLInputElement].files
Sure, should work

2023-02-14 16:04 UTC, lukasschreiber commented on utils.js
> +export const downloadJson = (name, text) => {
Will try, I think I have tried a bunch of solutions for the PDF download and the one I used was the one that worked best

2023-02-14 18:34 UTC, lukasschreiber commented on utils.js
> +export const downloadJson = (name, text) => {
Did not work for me, connection to the ws has been lost

2023-02-15 19:07 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/HomePage.scala
> +            val fileList = document.querySelector("#import-file").asInstanceOf[HTMLInputElement].files
Does not work with a Var

2023-02-16 14:10 UTC, merged