Webrtc
reform-org/reform pull request #31
Opened 2022-11-22 15:45 UTC by mohe2015

2022-11-22 23:18 UTC, JuliaSelua commented
Beim Client steht "Ask the host for their session token an insert it here" soll wahrscheinlich and sein?!

2022-11-23 07:13 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +import outwatch.*
Warum nutze wir hier * beim import, sonst überall _ ? * sollte die Scala 3 Syntax sein, oder? Sollten wir das dann nicht generell auf * umstellen?

2022-11-23 07:13 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +      h2(cls := "text-2xl text-center", "Ask the host for their session token an insert it here"),
Was Julia sagt: an -> and

2022-11-23 07:13 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +    private def onConnected(): Unit = {
Könnte man das hier nicht inlignen? (An den anderen Stellen wo es verwendet wird auch) - oder wird die onConnected Logik später noch komplexer?

2022-11-23 10:46 UTC, Oshgnacknak commented
Wir sollten uns zwischen `Connection String` und `Session Token` entscheiden.
Zwei synonyme Begriffe führen zu Verwirrung.
Ich wäre für `Session Token` und zwar Base64 kodiert, damit "normale" Nutzer nicht auf die Idee kommen, diese zu ändern.

2022-11-23 10:48 UTC, Oshgnacknak requested changes

2022-11-23 10:48 UTC, Oshgnacknak commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +      cls := "w-full",
Wie auch bei `HostPending` sollte hier eine Beschreibung stehen,
was der Nutzer tun muss.

2022-11-23 11:10 UTC, lukasschreiber commented
> 

Bin ich auch dafür, Session Token und base64

2022-11-23 14:49 UTC, Oshgnacknak commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +import outwatch.*
Ich würde hier den Unterstrich bevorzugen, da der auch in dem Rest der Code base genutzt wird.
Wenn wir das generell ändern wollen, sollten wir dafür ein eigenes Issue auf machen.

2022-11-23 15:34 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +    private def onConnected(): Unit = {
Okay

2022-11-23 16:23 UTC, mohe2015 commented on webapp/src/main/scala/webapp/pages/WebRTCHandling.scala
> +import outwatch.*
Werde ich mich denke drum kümmern, gibt ein Migration tool (https://docs.scala-lang.org/scala3/guides/migration/tooling-syntax-rewriting.html), das sowas kann und wo wir auch alles auf {} statt identation based setzen können, was wir ja präferieren, soweit ich weiß

2022-11-23 16:26 UTC, Oshgnacknak submitted a review, later dismissed

2022-11-23 16:49 UTC, merged