Add request for persistent storage
reform-org/reform pull request #313
Opened 2023-02-21 23:04 UTC by mohe2015

2023-02-21 23:08 UTC, mohe2015 commented
I don't know how we should do this UX-wise. Firefox will always ask the user and chrome will grant based on heuristics. We could e.g. ask when you click the add or edit buttons. I think that would be relatively nice.

2023-02-23 13:26 UTC, lukasschreiber commented
Aktuell fragt er gar nicht, oder?

2023-02-23 15:04 UTC, Oshgnacknak submitted a review, later dismissed

2023-02-23 15:06 UTC, lukasschreiber commented
Sehe ich das irgendwie?

2023-02-23 15:08 UTC, lukasschreiber requested changes

2023-02-23 15:08 UTC, lukasschreiber commented on js/src/main/scala/webapp/Main.scala
> +            "Application unusable as storage is not available. Your Browser does not support IndexedDB! Private tabs in Firefox don't work.",
Unklare Fehlermeldung

2023-02-23 15:10 UTC, lukasschreiber requested changes

2023-02-23 15:10 UTC, lukasschreiber commented on js/src/main/scala/webapp/npm/IndexedDB.scala
> +                ToastType.Error,
Würde das nur als Warning anzeigen, das ist ja nicht sooo dramatisch wenn man die seite regelmäßig nutzt

2023-02-23 15:10 UTC, lukasschreiber commented on js/src/main/scala/webapp/npm/IndexedDB.scala
> +          ToastType.Error,
Warning too

2023-02-23 15:11 UTC, mohe2015 commented
> Sehe ich das irgendwie?

If the next deploy suceeds firefox should ask you if you edit anything and other browsers should just show a toast on first edit.

2023-02-23 20:34 UTC, lukasschreiber approved these changes

2023-02-23 21:00 UTC, merged