Moritz sync counter
reform-org/reform pull request #33
Opened 2022-11-24 22:06 UTC by mohe2015

2022-11-24 22:15 UTC, mohe2015 commented
We need to not do this in the render method as it can reexecute and therefore creates lots of buggy behaviour

2022-11-24 22:20 UTC, mohe2015 commented
Replace LWWWins with the AddSubRegister

2022-11-28 21:24 UTC, mohe2015 commented
Requested a review from everybody as this will be a core part of our code

2022-11-28 21:52 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +  def createCounterRef(): Future[(rescala.default.Signal[DeltaBufferRDT[PosNegCounter]], rescala.default.Evt[Int])] = {
Wollen wir den Counter bzw andere Refs wirklich direkt in der WebRTCService.scala Datei haben? Fände es übersichtlicher die Refs extra zu machen

2022-11-28 22:28 UTC, Oshgnacknak requested changes

2022-11-28 22:28 UTC, Oshgnacknak commented on webapp/src/main/scala/webapp/pages/HomePage.scala
> +        onClick.foreach(_ => services.webrtc.counter.map(_(1).fire(1))),
This line is a bit convoluted.

2022-11-28 22:30 UTC, mohe2015 commented on webapp/src/main/scala/webapp/pages/HomePage.scala
> +        onClick.foreach(_ => services.webrtc.counter.map(_(1).fire(1))),
Hopefully improved a bit with https://github.com/reform-org/reform/pull/33/commits/1a5ad80007dd3668f421509db82c78ad73ec51a1
I wouldn't invest too much time as this code will heavily change probably anyways

2022-11-28 22:33 UTC, mohe2015 commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +  def createCounterRef(): Future[(rescala.default.Signal[DeltaBufferRDT[PosNegCounter]], rescala.default.Evt[Int])] = {
I think I would think about that as soon as we add a second thing. There is probably some behavior that can be extracted and some things will probably move into their views as these are normally not global objects.

 Moving it to the view now (which I read is your suggestion) will probably create rendering bugs again as these are created and deleted on rerenders and our code is probably not resilient against rerendering yet.

2022-11-28 22:35 UTC, mohe2015 commented
Remember to run `npm install` when testing this. The first build will currently take ages because it creates Scala.js bindings from Typescript dependencies. We may replace that workflow again in the future as we don't use it much but otherwise it seems like a nice thing to get correct typings.

2022-11-28 22:38 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +  def createCounterRef(): Future[(rescala.default.Signal[DeltaBufferRDT[PosNegCounter]], rescala.default.Evt[Int])] = {
Wieso in die Views? Man kann das doch einfach in eine eigene Klasse packen die dann von hier aus aufgerufen wird... ich finde wir sollten jetzt anfangen das ordentlich zu machen, nicht dass dann das bad practise von dieser temporären Geschichte kopiert und verändert wird und dann für etwas finales verwendet und dann persisted wird. Dieses Beispiel dient ja schließlich als Orientierung wie die ganze Syncgeschichte funktionieren soll, dann sollte es auch ein nicht nur funktionierendes, sondern auch ein ordentliches Beispiel sein.

2022-11-28 22:49 UTC, mohe2015 commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +  def createCounterRef(): Future[(rescala.default.Signal[DeltaBufferRDT[PosNegCounter]], rescala.default.Evt[Int])] = {
What do you want to put into a separate class? the counter creation and the `createCounterRef` function?

2022-11-28 22:56 UTC, lukasschreiber commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +  def createCounterRef(): Future[(rescala.default.Signal[DeltaBufferRDT[PosNegCounter]], rescala.default.Evt[Int])] = {
Ja genau, sodass der Kram so getrennt wie möglich von dem webrtc Service hier ist...

2022-11-29 15:28 UTC, lukasschreiber approved these changes
Gefällt mir

2022-11-30 15:02 UTC, mohe2015 commented on webapp/src/main/scala/webapp/services/CounterService.scala
> +          // this is async which means this is not robust
make this a FIXME comment

2022-11-30 15:02 UTC, mohe2015 commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +      // Praktisch wäre etwas wie crdt.observeDelta
remove this german comment which comes from upstream

2022-11-30 15:02 UTC, mohe2015 commented on webapp/src/main/scala/webapp/services/WebRTCService.scala
> +    var observers = Map[RemoteRef, Disconnectable]()
comment these

2022-11-30 18:59 UTC, Oshgnacknak approved these changes

2022-11-30 19:01 UTC, merged

2022-12-06 19:57 UTC, mohe2015 commented
11h