User story contract drafts
reform-org/reform pull request #378
Opened 2023-02-28 21:17 UTC by mohe2015

Fixes https://github.com/reform-org/reform/issues/301

2023-02-28 22:03 UTC, Oshgnacknak requested changes

2023-02-28 22:03 UTC, Oshgnacknak commented on js/src/main/scala/webapp/pages/EditContractsPage.scala
> +                            .getOrElse(0L)) / 86400000).toString + " days"
No magic constants, pls

2023-02-28 22:06 UTC, Oshgnacknak commented
Saving a draft (as draft - without finalizing) should route to the contract drafts page

2023-02-28 22:26 UTC, mohe2015 commented
> Saving a draft (as draft - without finalizing) should route to the contract drafts page

For me that works.

2023-03-01 11:39 UTC, Oshgnacknak approved these changes

2023-03-01 11:40 UTC, merged