some things, am too tired
reform-org/reform pull request #396
Opened 2023-03-01 21:53 UTC by lukasschreiber

2023-03-05 20:13 UTC, Oshgnacknak commented on js/src/main/scala/webapp/pages/ContractsPage.scala
> +  }.flatten
Again, nested flatten should not be necessary when using `.value`

2023-03-05 20:24 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/ContractDraftsPage.scala
> +        }.flatten,
removed that, leftover from refactoring

2023-03-05 20:24 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/ContractsPage.scala
> +  }.flatten
I think this flatten is needed...

2023-03-05 20:26 UTC, lukasschreiber commented on js/src/main/scala/webapp/pages/ContractsPage.scala
> +  }.flatten
if I remove one of the signals it does not compile anymore.

2023-03-05 23:08 UTC, mohe2015 requested changes

2023-03-05 23:08 UTC, mohe2015 commented on js/src/main/scala/webapp/entity/UIAttribute.scala
> +class UIFormat[EntityType](val condition: (id: String, entity: EntityType) => Signal[Boolean], val classes: String) {
I don't really like introducing this change for this special case but we'll see how it will develop.

2023-03-05 23:08 UTC, mohe2015 commented on js/src/main/scala/webapp/pages/ContractsPage.scala
> +  def getMoneyPerHour(id: String, contract: Contract)(using repositories: Repositories): Signal[BigDecimal] =
pls document what these two methods do and maybe reduce the code duplication

2023-03-06 13:33 UTC, mohe2015 approved these changes

2023-03-06 13:34 UTC, merged