Settings
reform-org/reform pull request #461
Opened 2023-03-10 21:15 UTC by JuliaSelua

2023-03-10 22:05 UTC, lukasschreiber commented
Am PC sollen die Buttons noch text haben, du kannst die buttons bzw. den text mit sm:hidden bzw. md:hidden oder lg:hidden ausblenden

2023-03-10 22:07 UTC, lukasschreiber commented
![Screenshot_20230310_230643_Chrome.jpg](https://user-images.githubusercontent.com/31158920/224437222-8db62238-0ede-4b01-a596-1a17fcea605f.jpg)

Ich würde die buttons linksbündig machen auf mobile

2023-03-10 22:08 UTC, lukasschreiber commented
![Screenshot_20230310_230608_Chrome.jpg](https://user-images.githubusercontent.com/31158920/224437285-68c6c29f-7e70-493a-8092-32bb510e75fa.jpg)

Das sieht auf mobile bisschen komisch aus, durch den großen Abstand zum Rand und zu den boxen verliert man sehr platz

2023-03-10 22:09 UTC, lukasschreiber commented
Das choose file sollte auch in unserem design sein...
Und die erklär texte würde ich einfach in einer grauen schrift machen und ganz unauffällig

2023-03-10 22:10 UTC, lukasschreiber commented
Im filter auf mobile sind die inputs auch zu breit

2023-03-10 22:24 UTC, JuliaSelua commented
> Am PC sollen die Buttons noch text haben, du kannst die buttons bzw. den text mit sm:hidden bzw. md:hidden oder lg:hidden ausblenden

Sollte eigentlich auch der Fall sein
![image](https://user-images.githubusercontent.com/104761063/224439395-4a1540a4-8dc5-4e2a-aad1-43a11fc3333e.png)
oder meinst du  was anderes?

2023-03-10 22:32 UTC, lukasschreiber commented
Ah ups, dann ist gut 😀On 10 Mar 2023 23:24, JuliaSelua ***@***.***> wrote:

Am PC sollen die Buttons noch text haben, du kannst die buttons bzw. den text mit sm:hidden bzw. md:hidden oder lg:hidden ausblenden

Sollte eigentlich auch der Fall sein

oder meinst du  was anderes?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2023-03-12 11:45 UTC, mohe2015 requested changes
Probably unrelated to this PR but if you click new contract and then save and then reload the page another new contract is created and not the current contract is shown. This is probably because the save button doesn't update the url to the edit page

2023-03-12 11:45 UTC, mohe2015 commented on js/src/main/scala/webapp/components/NavigationHeader.scala
>          "Settings",
maybe rename this to "Setup"?

2023-03-12 11:45 UTC, mohe2015 commented on js/src/main/scala/webapp/pages/SettingsPage.scala
> +              p(
remove all these or add a better text

2023-03-12 11:45 UTC, mohe2015 commented on js/src/main/scala/webapp/pages/SettingsPage.scala
> +                    val fileList = document.querySelector("#import-file").asInstanceOf[HTMLInputElement].files
![image](https://user-images.githubusercontent.com/13287984/224542243-6bd34381-0055-41e6-bc63-92ab1f4f2697.png)

2023-03-12 14:02 UTC, lukasschreiber commented
> Probably unrelated to this PR but if you click new contract and then save and then reload the page another new contract is created and not the current contract is shown. This is probably because the save button doesn't update the url to the edit page

Habs trotzdem mal hier gefixed

2023-03-12 14:06 UTC, mohe2015 submitted a review, later dismissed

2023-03-12 14:09 UTC, Oshgnacknak commented on js/src/main/scala/webapp/components/common/MultiSelect.scala
> +    required,
sure, we want that twice?
Is this a merge error?

2023-03-12 14:16 UTC, Oshgnacknak commented on js/src/main/scala/webapp/components/common/MultiSelect.scala
> +    required,
I think i see why.
It would still be nicer, if we used assignment syntax here:
```scala
required = required,
styleValidity = required
```

2023-03-12 14:18 UTC, mohe2015 commented on js/src/main/scala/webapp/components/common/MultiSelect.scala
> +    required,
Will change

2023-03-12 14:35 UTC, merged